# Generated by Django 4.2.5 on 2023-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_APP', '0002_alter_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='correctOption',
            field=models.IntegerField(max_length=250, null=True),
        ),
    ]
