# Generated by Django 4.2.5 on 2023-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_APP', '0003_options_is_selected_questions_correctoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='is_selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
