# Generated by Django 4.2.5 on 2023-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_APP', '0004_alter_options_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
