# Generated by Django 4.2.5 on 2023-09-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA_APP', '0005_alter_options_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correctOption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_question', to='QA_APP.options'),
        ),
    ]
